name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

# Quais tarefas queremos executar?
jobs: 
  #tarefa
  lint: 
    runs-on: ubuntu-latest
    steps:
        - name: "Lint"
          run: "echo 'Olá'"