name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

# Quais tarefas queremos executar?
jobs: 
  #tarefa
  lint: 
    runs-on: ubuntu-latest
    steps:
        # [Common CI/CD step]
        - uses: actions/checkout@v3
        # ===================
        - name: "Install Dependences"
          run: "npm install"
        - name: "Lint"
          run: "npm run lint"